Repository RegioHelden/django-kafka, pull requests merged in 2025-04, with the labels that each got.

#64 Test against Django 5.2
  .github/workflows/workflow.yaml
Labels: enhancement

#65 Release v0.6.0
  CHANGELOG.md
  pyproject.toml
Labels: skip-changelog

#71 Move project version to standalone file
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/workflow.yaml
  pyproject.toml
  version
Labels: skip-changelog

#72 Preparations for modulesync rollout
  .sync.yml
  Dockerfile
  compose.yaml
  system_dependencies.txt
Labels: infrastucture

#73 Updates from modulesync
  .devcontainer/compose.yaml
  .devcontainer/devcontainer.json
  .github/dependabot.yml
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
  .gitignore
  .vscode/tasks.json
  Dockerfile
  LICENSE
  compose.yaml
  example/__init__.py
  manage.py
  pyproject.toml
Labels: infrastucture

#75 Updates from modulesync
  .github/dependabot.yml
Labels: infrastucture

#76 Updates from modulesync
  .github/dependabot.yml
  .github/workflows/build-and-publish.yaml
  .github/workflows/tag-release.yaml
Labels: infrastucture

#77 Updates from modulesync
  .devcontainer/devcontainer.json
Labels: infrastucture

#80 Updates from modulesync
  compose.yaml
  pyproject.toml
Labels: infrastucture

#81 Updates from modulesync
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
Labels: infrastucture

#82 Release v0.7.0
  CHANGELOG.md
  version
Labels: skip-changelog

#83 Updates from modulesync
  Dockerfile
Labels: infrastucture

#85 Remove unused version from init file
  django_kafka/__init__.py
Labels: enhancement
