Repository RegioHelden/django-kafka, pull requests merged in 2025-07, with the labels that each got.

#114 Update uv to 0.7.19
  Dockerfile
Labels: infrastucture

#109 feat: implement relations resolver.
  .github/workflows/workflow.yaml
  README.md
  compose.yaml
  django_kafka/__init__.py
  django_kafka/admin.py
  django_kafka/conf.py
  django_kafka/consumer/consumer.py
  django_kafka/consumer/topics.py
  django_kafka/exceptions.py
  django_kafka/migrations/0002_waitingmessage.py
  django_kafka/models.py
  django_kafka/registry.py
  django_kafka/relations_resolver/__init__.py
  django_kafka/relations_resolver/daemon/__init__.py
  django_kafka/relations_resolver/daemon/temporal.py
  django_kafka/relations_resolver/processor/__init__.py
  django_kafka/relations_resolver/processor/base.py
  django_kafka/relations_resolver/processor/model.py
  django_kafka/relations_resolver/relation.py
  django_kafka/relations_resolver/resolver.py
  django_kafka/relations_resolver/temporalio/__init__.py
  django_kafka/relations_resolver/temporalio/activities.py
  django_kafka/relations_resolver/temporalio/schedules.py
  django_kafka/relations_resolver/temporalio/workflows.py
  django_kafka/tests/relations_resolver/__init__.py
  django_kafka/tests/relations_resolver/factories.py
  django_kafka/tests/relations_resolver/test_model_processor.py
  django_kafka/tests/relations_resolver/test_model_relation.py
  django_kafka/tests/relations_resolver/test_queryset.py
  django_kafka/tests/relations_resolver/test_relation.py
  django_kafka/tests/relations_resolver/test_relation_type.py
  django_kafka/tests/relations_resolver/test_resolver.py
  django_kafka/tests/test_consumer/test_consumer.py
  django_kafka/tests/utils.py
  django_kafka/topic/__init__.py
  django_kafka/utils/message.py
  example/apps.py
  example/migrations/0001_initial.py
  example/migrations/__init__.py
  example/models.py
  example/settings.py
  pyproject.toml
  requirements-ci.txt
  requirements-test.txt
Labels: feature

#115 fix: `ModelMessageProcessor._aget_missing_relation` wrong return value.
  django_kafka/relations_resolver/processor/model.py
  django_kafka/tests/relations_resolver/test_model_processor.py
  pyproject.toml
  requirements-test.txt
Labels: bug

#116 Release v0.10.0
  CHANGELOG.md
  version
Labels: skip-changelog

#118 Release v0.11.0
  CHANGELOG.md
  version
Labels: skip-changelog

#123 Update test dependencies
  requirements-test.txt
Labels: infrastructure

#124 Require postgres container from modulesync
  .sync.yml
Labels: infrastructure

#127 Update uv to 0.7.21
  Dockerfile
  compose.yaml
Labels: infrastucture

#129 feat: improve debug logging, refs #128
  django_kafka/consumer/consumer.py
Labels: feature

#133 Update uv to 0.8.3
  Dockerfile
Labels: infrastucture
