Repository RegioHelden/django-kafka, pull requests merged in 2025-05, with the labels that each got.

#86 Update uv to 0.7.3
  Dockerfile
Labels: infrastucture

#87 Update uv to 0.7.4
  Dockerfile
Labels: infrastucture

#89 fix: resume partitions should resume at the paused offsets, refs #88
  django_kafka/consumer/managers.py
  django_kafka/tests/test_consumer/test_consumer.py
  django_kafka/tests/test_consumer/test_managers.py
Labels: bug

#90 Release v0.8.0
  CHANGELOG.md
  version
Labels: skip-changelog

#92 fix: add retry setting to log every Nth attempt and add more info headers to dead letter topic, refs #91
  README.md
  django_kafka/consumer/consumer.py
  django_kafka/dead_letter/header.py
  django_kafka/dead_letter/topic.py
  django_kafka/retry/consumer.py
  django_kafka/retry/settings.py
  django_kafka/retry/topic.py
  django_kafka/tests/test_consumer/test_consumer.py
  django_kafka/tests/test_dead_letter/test_topic.py
  django_kafka/tests/test_retry/test_consumer.py
  django_kafka/tests/test_retry/test_retry.py
  django_kafka/tests/test_retry/test_topic.py
Labels: feature

#93 Release v0.9.0
  CHANGELOG.md
  version
Labels: skip-changelog

#95 Update uv to 0.7.6
  Dockerfile
Labels: infrastucture

#96 Update uv to 0.7.7
  Dockerfile
Labels: infrastucture

#98 Update uv to 0.7.8
  Dockerfile
Labels: infrastucture
